apiVersion: v1
kind: Pod
metadata:
  name: hello-test
  labels:
    app: web
spec:
  netNamespace: test
  containers:
    - name: helloworld
      image: autilite/http-counter
      ports:
        - containerPort: 9000
